apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram-receiver
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "1895525228"
        disableResolveMessage: false
